ScriptParser: Fix broken arg count errors
When redoing some screenshots, I tried to reproduce the following error message:

  An error occurred in the wizard script:
  Line 15:	    Else 'What am I doing here?'
  Error:	(Line 15, Column 33): Too many arguments to Keyword 'Else':  got 1, expected 0.

However, I only managed to create the following:

  An error occurred in the wizard script:
  Line 15:	    Else 'What am I doing here?'
  Error:	(Line 15, Column 33): Too many arguments to Keyword 'self.text':  got 1, expected 0.

Turns out that the error reporting here has been broken since
40e3faaba167c18d58531ba417c9fe769a445182 back in 2011.
Also wrapped the code I touched.