Disabling locale to avoid nasty traceback:
Wrye Bash starting
Using Wrye Bash Version 307
Python version: 2.7.10
wxPython version: 3.0.2.0 msw (classic)
input encoding: None; output encoding: None; locale: ('en_US', 'cp1253')
filesystem encoding: mbcs
Searching for game to manage:
bush.py   71 _supportedGames: Detected the following supported games via Windows Registry:
bush.py   73 _supportedGames:  oblivion: C:\GAMES\TESIV\Oblivion
bush.py   73 _supportedGames:  skyrim: C:\GAMES\Skyrim
bush.py  131 _detectGames: Detecting games via the -o argument, bash.ini and relative path:
bush.py  137 _detectGames: Set game mode to oblivion based on sOblivionPath setting in bash.ini:  C:\GAMES\TESIV\Oblivion
bush.py  172 setGame: No preferred game specified.
bush.py  152 __setGame:  Using oblivion game: C:\GAMES\TESIV\Oblivion
testing UAC
__init__.py 7481 initDirs: Using libbsa API version: 2.0.0
mods_metadata.py  219 __init__: Using LOOT API version: 0.6.0
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 428, in main
    frame = app.Init() # Link.Frame is set here !
  File "bash\basher\__init__.py", line 4316, in Init
    size=settings['bash.frameSize'])
  File "bash\basher\__init__.py", line 3906, in __init__
    self.SetStatusBar(BashStatusBar(self))
  File "bash\basher\__init__.py", line 3669, in __init__
    self.UpdateIconSizes()
  File "bash\basher\__init__.py", line 3707, in UpdateIconSizes
    self._addButton(link)
  File "bash\basher\__init__.py", line 3681, in _addButton
    gButton = link.GetBitmapButton(self,style=wx.NO_BORDER)
  File "bash\basher\app_buttons.py", line 657, in GetBitmapButton
    image=staticBitmap(window, special='undo', size=(size,size)))
  File "bash\balt.py", line 509, in staticBitmap
    return bmp(wx.ART_UNDO,wx.ART_TOOLBAR,size)
  File "C:\_\Python27\lib\site-packages\wx-3.0-msw\wx\_misc.py", line 3013, in ArtProvider_GetBitmap
    return _misc_.ArtProvider_GetBitmap(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "strcmp(setlocale(LC_ALL, NULL), "C") == 0" failed at ..\..\src\common\intl.cpp(1449) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!